"""added updated at to certificate versioning

Revision ID: 912f76ed6a9b
Revises: fc6f70b2037f
Create Date: 2026-04-27 09:59:58.517507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912f76ed6a9b'
down_revision: Union[str, Sequence[str], None] = 'fc6f70b2037f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_versions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_versions', 'updated_at')
    # ### end Alembic commands ###
