"""Initial migration

Revision ID: b1a2cc384525
Revises: 
Create Date: 2026-04-27 09:45:11.925179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a2cc384525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_certificate_id'), 'audit_logs', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issuer_id', sa.UUID(), nullable=False),
    sa.Column('holder_email', sa.String(length=255), nullable=False),
    sa.Column('holder_name', sa.String(length=255), nullable=False),
    sa.Column('certificate_title', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.Column('qr_nonce', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_nonce')
    )
    op.create_index('idx_certificate_expiry_valid', 'certificates', ['expires_at', 'revoked_at'], unique=False)
    op.create_index('idx_certificate_issuer_active', 'certificates', ['issuer_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_certificates_expires_at'), 'certificates', ['expires_at'], unique=False)
    op.create_index(op.f('ix_certificates_holder_email'), 'certificates', ['holder_email'], unique=False)
    op.create_index(op.f('ix_certificates_issuer_id'), 'certificates', ['issuer_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_certificates_issuer_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_holder_email'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_expires_at'), table_name='certificates')
    op.drop_index('idx_certificate_issuer_active', table_name='certificates')
    op.drop_index('idx_certificate_expiry_valid', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_certificate_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
