"""Created certificate versioning

Revision ID: fc6f70b2037f
Revises: 42d2383220de
Create Date: 2026-04-27 09:58:12.217154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc6f70b2037f'
down_revision: Union[str, Sequence[str], None] = '42d2383220de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('update_reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id', 'version_number', name='uq_cert_version')
    )
    op.create_index('idx_cert_version_cert', 'certificate_versions', ['certificate_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_certificate_versions_certificate_id'), 'certificate_versions', ['certificate_id'], unique=False)
    op.add_column('certificates', sa.Column('current_version', sa.Integer(), nullable=False))
    op.add_column('certificates', sa.Column('last_updated_by', sa.UUID(), nullable=True))
    op.add_column('certificates', sa.Column('update_reason', sa.String(length=500), nullable=True))
    op.add_column('certificates', sa.Column('version_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_certificate_version', 'certificates', ['id', 'current_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_certificate_version', table_name='certificates')
    op.drop_column('certificates', 'version_history')
    op.drop_column('certificates', 'update_reason')
    op.drop_column('certificates', 'last_updated_by')
    op.drop_column('certificates', 'current_version')
    op.drop_index(op.f('ix_certificate_versions_certificate_id'), table_name='certificate_versions')
    op.drop_index('idx_cert_version_cert', table_name='certificate_versions')
    op.drop_table('certificate_versions')
    # ### end Alembic commands ###
